<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NA</name>
   <tag></tag>
   <elementGuidId>49758cde-5746-4cfa-9e6b-d80f5ce7cb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.payment-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react_0HM7DNR8ELV9H']/div/div[2]/div[3]/div/div/div/div/div/div[9]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-status</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N/A</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HM7DNR8ELV9H&quot;)/div[1]/div[@class=&quot;order-history-sec-list&quot;]/div[@class=&quot;ordrhist-list-bodysec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ordrhist-list-innerbody&quot;]/div[@class=&quot;order-history-sec-list&quot;]/div[@class=&quot;ordrhist-list-innerbody&quot;]/div[@class=&quot;ordrhist-list-bodyrow loadedstatus&quot;]/div[@class=&quot;ordrhist-status-col&quot;]/span[@class=&quot;payment-status&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react_0HM7DNR8ELV9H']/div/div[2]/div[3]/div/div/div/div/div/div[9]/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order request created'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N/A']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
