<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_item_category</name>
   <tag></tag>
   <elementGuidId>885a68e1-d6ed-4391-aade-79be9055c57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div[2]/div/div/form/div/div[1]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[1]/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/form/div/div[1]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[1]/label</value>
   </webElementProperties>
</WebElementEntity>
