<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_selectedvalue_3</name>
   <tag></tag>
   <elementGuidId>8aed5979-9d63-4ead-a583-fbd2d12e5fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[6]/div/div/div/div[3]/div/ul[3]/li/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/div/div[3]/div/ul[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/div/ul[3]/li/span</value>
   </webElementProperties>
</WebElementEntity>
