<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_selectedvalue_1</name>
   <tag></tag>
   <elementGuidId>5c47855c-4e5e-4352-849e-762931433c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[6]/div/div/div/div[3]/div/ul[1]/li/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/div/div[3]/div/ul[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/div/ul[1]/li/span</value>
   </webElementProperties>
</WebElementEntity>
